alfresco-docker-alfresco-pdf-renderer/pom.xml
alfresco-docker-imagemagick/pom.xml
alfresco-docker-libreoffice/pom.xml
alfresco-docker-tika/pom.xml
alfresco-transformer-base/pom.xml

- noticed when running "mvn clean install"
- exclude "android-json-0.0.20131108.vaadin1.jar" (rather than "json-20160212.jar") for "spring-boot-starter-test"

ATS-223: ATS: T-Engines: fix warn for duplicate org.json.JSONObject on classpath

---

alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java

- rename endpoint since '/info' is already used by Spring Boot
- fix config file loading

ATS-434 : Implement `/transform/config` endpoint in T-Engines

---

alfresco-transformer-base/src/main/java/org/alfresco/transformer/QueueTransformService.java
alfresco-transformer-base/src/test/java/org/alfresco/transformer/QueueTransformServiceTest.java

- code refactoring:
-- if successful -> return the object ( Optional.ofNullable(request) )
-- if not successful -> throw an exception (instead of sending an error message on the queue)
- when calling 'convert()' method, catch this exception and send a T-Reply with error message on the queue

ATS-250 : ATS: T-Engines: Improve the convert message error handling (T-Base)

---

alfresco-docker-alfresco-pdf-renderer/pom.xml
alfresco-docker-imagemagick/pom.xml
alfresco-docker-libreoffice/pom.xml
alfresco-docker-tika/pom.xml
alfresco-docker-transform-misc/pom.xml
alfresco-transformer-base/pom.xml
pom.xml

- temp workaround attempt to update from dom4j 1.6.1 to 2.1.1
- transitive dependency (alfresco-core <- spring-surf-core-configservice)
- workaround should be removed once REPO-4514 resolved (future alfresco-core <- spring-surf)

ATS-481: temp workaround for transitive dependency

---

_ci/build.sh
alfresco-docker-tika/pom.xml
pom.xml

- publish SNAPSHOT artifacts from the master branch
- exclude quartz dependency from tika-parsers

ATS-534 : Security - Vulnerability in Quartz - CVE-2019-13990

---

alfresco-docker-tika/src/main/java/org/alfresco/transformer/TikaController.java

- add default "UTF-8" target encoding
- restore previously default values for the other options

ATS-515: Default options for TIKA when called through ATS

---

alfresco-docker-tika/src/main/resources/engine_config.json

Sets priorities on 5 Tika transform routes so they are not used if LibreOffice is available. This currently has no impact on the Transform Service (priorities are not used for routing), but does on repository LocalTransforms as the wrong T-Engine is selected.
Fixes the routes identified as having the same priority in the last table of https://issues.alfresco.com/jira/browse/REPO-4452?focusedCommentId=636603&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-636603

REPO-4452 Local transformer pipelines - missing priorities

---

alfresco-docker-alfresco-pdf-renderer/pom.xml
alfresco-docker-imagemagick/pom.xml
alfresco-docker-libreoffice/pom.xml
alfresco-docker-tika/pom.xml
alfresco-docker-transform-misc/pom.xml

- ActiveMQ 5.15.8 (from 5.15.6)

ATS-648: Update ActiveMQ tests

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile

- fallout from ATS-693
- update Dockerfile to use same Java Base Image as other x5 (ATS-711) 
- see also DEPLOY-924 / ATS-655

ATS-655: Update AIO java base image

---

.travis.yml
alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
alfresco-transform-misc/alfresco-transform-misc/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transformer-base/pom.xml
pom.xml

- bump pom.xml to 2.2.0-TEST1-SNAPSHOT
- update time_wait from 30 to 45 mins (since 2.2.0-A1 may have timed-out)

ATS-676 - test release of T-Core (T-Engines) 2.2.0-TEST1 [trigger release]

---

.travis.yml
_ci/static_analysis.sh

- ie. only upload runnable jars (Spring Boot apps) x6 (= x1 AIO core T-Engine  + x5 individual core T-Engines)
- see also ATS-711 / ATS-696 / ATS-468

ATS-718: Tweak Veracode SAST to only upload & scan delivered artefacts

---

alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/java/org/alfresco/transformer/executors/JodConverterSharedInstance.java

Fix NPE in libreoffice when the external files are not present and debug is enabled.

ATS-714: Fix libreoffice NPE when debug enabled

---

_ci/cache_artifacts.sh

Update the LibreOffice version in the cache_artifacts.sh to 6.3.5

ATS-725(REPO-4919) Update LibreOffice to 6.3.5 in cache_artifacts.sh

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/templates/transformForm.html

Issues related to HTML test form tidy-up:
- Alfresco PDF Renderer Test Transformation is missing targetMimetype field
- LibreOffice Test Transformation is missing sourceMimetype field
- Miscellaneous Transformers Test Transformation only fields like sourceMimetype and targetMimetype are required, but all fields are marked as required
- ImageMagick Test Transformation missing targetMimetype and sourceMimetype

ATS-720: Fix HTML Test Form

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java

* Provide a way for Legacy ACS transformers to specify the transform to perform, rather than letting the T-Engine to determine it using the engine config.

ATS-707: add transformName override

---

alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/resources/libreoffice_engine_config.json

Increase Office->PDF default size limits (via LibreOffice)
- increase OOXML formats (to be equivalent to current classic formats plus a bit)
- make docx/xlsx 15 MiB
- make pptx 40 MiB
- also increase classic format by additional 20% over OOXML formats
- make docx/xlsx 18 MiB
- make pptx 48 MiB

ACS-113: Increase Office->PDF default size limits (via LibreOffice)

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile

- note: aligns with ACS Repo 6.2.1-A4 and higher (note: post RC3)

ACS-99: Update to most current Java Base Image (for OpenJDK 11.0.7 / CentOS 7)

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/java/org/alfresco/transformer/ImageMagickController.java
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/java/org/alfresco/transformer/LibreOfficeController.java
alfresco-transform-misc/alfresco-transform-misc-boot/src/main/java/org/alfresco/transformer/MiscController.java
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/java/org/alfresco/transformer/AlfrescoPdfRendererController.java
alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/TikaController.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformController.java

- Added a default implementation of AbstractTransformerController#transform(java.lang.String, java.lang.String, java.lang.String, java.util.Map<java.lang.String,java.lang.String>, java.io.File, java.io.File) for existing
T-Engines that override transform(HttpServletRequest...) and processTransform(...).
I would get rid of the code duplication in alfresco-ai-transformers. There is some rework required in its' test class mocking anyway. From the log: "There is already 'aiController' bean method ... transform(". The test code appear to assume there can be only be one method called transform. This is no longer the case. I'm guessing it is a small fix for someone with the AWS dev env set up, so it might make sense to fix up the code duplication at the same time.

ATS-777 / REPO-4334: Move metadata extraction into T-Engines

---

alfresco-transformer-base/src/main/java/org/alfresco/transformer/messaging/MessagingInfo.java
alfresco-transformer-base/src/main/resources/application.yaml

- note: in the meantime, workaround(s) exist including simply using ACTIVEMQ_URL env var

ATS-738 / MNT-21613: Allow option to use -DACTIVEMQ_URL (without needing to also set -Dactivemq.url)

---

alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaTransformationIT.java
alfresco-transform-tika/alfresco-transform-tika/src/main/resources/tika-config.xml

The application/vnd.apple.keynote -> text/plain transformation has been found to fail after switching a new version of tika in ATS-801
The previous version of tika would use a org.apache.tika.parser.pkg.PackageParser but the new version uses an empty parser producing an empty target file, which now causes test failures in the new ATS integration tests.

ATS-816: Fix tika apple keynote

---

alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/java/org/alfresco/transformer/AIOTransformRegistryTest.java
alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/resources/misc_engine_config.json
alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/resources/tika_engine_config.json
alfresco-transform-misc/alfresco-transform-misc-boot/src/test/java/org/alfresco/transformer/MiscControllerTest.java
alfresco-transform-misc/alfresco-transform-misc-boot/src/test/resources/misc_engine_config.json
alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/metadataExtractors/HtmlMetadataExtractor.java
alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/metadataExtractors/RFC822MetadataExtractor.java
alfresco-transform-misc/alfresco-transform-misc/src/main/resources/misc_engine_config.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/tika_engine_config.json
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/TikaJavaExecutor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/resources/tika_engine_config.json
alfresco-transformer-base/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractMetadataExtractor.java
pom.xml

Linked to: REPO-5219 Allow AGS AMP to specify metadata extract mapping
Added an extractMapping transform option to all metadata extractors to override the default one.

ATS-829  Release T-Engines 2.3.6

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerTikaTest.java
alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/resources/tika_engine_config.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaControllerTest.java
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/tika_engine_config.json
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/TikaJavaExecutor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractTikaMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/PoiMetadataExtractor.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractMetadataExtractor.java

Bug found while reviewing documents on how to create a custom metadata extractor. The original refactor had left the repo doing the mapping. It should have been passing the fully qualified repo properties to the T-Engine to do the mapping.
Linked to:
* https://github.com/Alfresco/alfresco-community-repo/pull/227
* https://github.com/Alfresco/acs-packaging/pull/1826

REPO-5191 Bug: T-Engine should provide mapping rather than the repo.

---

pom.xml

Bumps spring-boot-starter-parent from 2.4.1 to 2.4.2.

ATS-1196: Update Spring Boot Starter to 2.4.2

---

alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/java/org/alfresco/transformer/AIOTransformRegistryTest.java
alfresco-transform-misc/alfresco-transform-misc-boot/src/test/java/org/alfresco/transformer/MiscControllerTest.java
alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/TextToPdfContentTransformer.java
alfresco-transform-misc/alfresco-transform-misc/src/test/java/org/alfresco/transformer/transformers/TextToPdfContentTransformerTest.java
pom.xml

* Introduce more flexible reading of UTF-16 data, where there may be a BOM where the
spec says there should not be one or the BOM is clearly wrong when looking at the
following characters. The https://en.wikipedia.org/wiki/UTF-16 write up is nice an clear.
* Includes identical correction in data setup in AIOTransformRegistryTest and
MicsControllerTest for a problem found in TextToPdfContentTransformerTest.
* Includes upgrade to latest pdfbox: 2.0.22

MNT-20626 XML files having UTF-16LE and UTF-16BE can't be previewed

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile

- to resolve 2 medium (at time of writing) in quay.io
- update to CentOS 7 to 8 (aligned with Repo decision)

ATS-863: Update to latest Java Base Image on CentOS 8 (& Open JDK 11.0.10)

---

alfresco-transformer-base/src/main/java/org/alfresco/transformer/executors/Transformer.java

When an exception occurs in transformations we will get the message and and internal server error. However the cause is lost. In my case I got a NullPointerException in the core-aio transform, but no info where it originated from. With this change the cause will be added to the new TransformException.

Include throwable cause in TransformException

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOCustomConfig.java
alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml
alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/TikaController.java
alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/application-default.yaml
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaControllerTest.java
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/Tika.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/TikaJavaExecutor.java
alfresco-transform-tika/alfresco-transform-tika/src/test/java/org/alfresco/transformer/executors/TikaJavaExecutorTest.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/util/RequestParamMap.java
docs/external-engine-configuration.md

See [MNT-22082](https://alfresco.atlassian.net/browse/MNT-22082)
The hanging is caused only when `notExtractBookmarkText` is set to false.
A workaround was added to repo for local transforms only and was not applied to ATS. This workaround set the default value of `notExtractBookmarkText` to true.  As of 7.0, local transforms have been removed. This PR will now add a similar workaround for both the Tika and AIO T-engines, and by extension ATS.
A new constructor has been added to the `TikaController` to provide the new spring config. The original constructor has been maintained so that there are no issue with backward compatibility.
The creation of the `TikaJavaExecutor` has been moved to "singleton pattern" as the injection of the `@Value` happens after the instantiation of the …

MNT-22082 transformation of pdf to text hang

---

pom.xml

- small PR prior to DependABot prompted updates, such as:
-- https://github.com/Alfresco/alfresco-transform-core/pull/351#pullrequestreview-621417662
-- https://github.com/Alfresco/alfresco-transform-core/pull/368
-- ...
- in most cases, these versions should match
-- only exception is previous occasions where data-bind specific version was released ahead of core

ATS: Update libraries (DependABot) etc - fix jackson core/data-bind version mismatch

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile

- note: sha256 id is used
- update prefix moniker to document the JDK version (& match quay.io tag name)

ATS: Tweak Java Base Image references

---

alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/TikaController.java

Allows for object creation to be done on startup, instead of first transform call.

Refactor TikaController

---

alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java

This will provide the file downloaded from Share File Store with the expected file extension provided in the `TransformRequest`, instead of null, if it is not present in the Share File Store response.

ACS-1677 Provide file extension from JMS request if missing in SFS

---

alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/AIOTransformRegistry.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java
pom.xml

* Addition of logWarn method
**Depends on a new version of alfresco-transform-model (see https://github.com/Alfresco/alfresco-transform-model/pull/93)**

ACS-1778 Common transform routing code for Repo and t-router

---

_ci/init.sh
_ci/settings.xml

- use QUAY_USERNAME  (set to "alfresco+travis_ci")
- (instead of old hard-coded "alfresco+bamboo" robot account that no longer exists)
- update settings.xml to use env vars for usernames (consistent with other projects)

ATS-970: Fix build after Travis secrets rotation

---

alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.3g2_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.3gp_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.m4v_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.mov_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.mp4_metadata.json
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractTikaMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/DWGMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/MP3MetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/MailMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/OfficeMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/OpenDocumentMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/TikaAudioMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/tika/parsers/ExifToolParser.java
pom.xml

1. Tika 2.x is more accurate in extracting metadata from media containers.
2. Deprecated code (we relied on) has been removed. New replacement has been found.
3. Internal Metadata representation doesn't match Tika 1.x
* "Bare" properties like (`Creation-Date`, `Edit-Time`, `Last-Modified`, `Last-Save-Date`) are no longer available in favour of Dublin Core properties.
* Dublin Core properties have been used to fulfil the default Alfresco mappings.
4. There is no single `Creator` property anymore. For backward compatibility the OpenOffice Parser has been extended.
Tika 2.1.0 still depend on the POI 4.1.2 so we shouldn't upgrade it.

ATS-969 Tika upgrade 1.x -> 2.x

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickControllerTest.java
alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/java/org/alfresco/transformer/LibreOfficeControllerTest.java
alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
alfresco-transform-misc/alfresco-transform-misc/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/test/java/org/alfresco/transformer/AlfrescoPdfRendererControllerTest.java
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaControllerTest.java
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transformer-base/pom.xml
alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/QueueTransformService.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/config/WebApplicationConfig.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/messaging/TransformReplySender.java
alfresco-transformer-base/src/main/resources/application.yaml
alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java
pom.xml

By default T-Engines now only provide TransformerDebug DEBUG messages, rather than the original detailed request and reply messages, which are still available as TRACE.

ACS-2002 Enhance T-Router debug

---

alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.3g2_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.3gp_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.m4v_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.mov_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.mp4_metadata.json
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractTikaMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/DWGMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/MP3MetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/MailMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/OfficeMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/OpenDocumentMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/TikaAudioMetadataExtractor.java
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/tika/parsers/ExifToolParser.java
pom.xml

Revert ATS-969 Tika upgrade 1.x -> 2.x (#493)
As the build is deleting the following, resulting in the release job failure
D	alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/license/THIRD-PARTY.properties
D	alfresco-transform-core-aio/alfresco-transform-core-aio/src/license/THIRD-PARTY.properties
D	alfresco-transform-tika/alfresco-transform-tika-boot/src/license/THIRD-PARTY.properties
D	alfresco-transform-tika/alfresco-transform-tika/src/license/THIRD-PARTY.properties

[trigger release] 2.5.5-A1

---

alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/application-default.yaml
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaMetadataExtractsIT.java
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odf_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odg_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odt_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.otg_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.ott_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.pdf_metadata.json
alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.sxw_metadata.json
alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/AbstractTikaMetadataExtractor.java
alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractMetadataExtractsIT.java
alfresco-transformer-base/src/test/java/org/alfresco/transformer/TestFileInfo.java
pom.xml

Original PR https://github.com/Alfresco/alfresco-transform-core/pull/506 was merged to master where it failed. There had been no build of the PR before the merge, which is why this branch has been created.
With the upgrade of Tika from 2.2.0 to 2.2.1, the deprecated OfficeOpenXMLCore.SUBJECT metadata value became  null and the replacement TikaCoreProperties.SUBJECT became a multi value in a few of our test cases. For backward compatibility with very old versions of Alfresco, we have historically been added a number of extra values including "subject" and "description" back into the raw metadata, before mapping them onto Alfresco properties. These values existed in the original version of Tika used by Alfresco, so it is possible there are custom mappings out there that using them.
To …

Repeat Bump dependency.tika.version from 2.1.0 to 2.2.1

---

.github/dependabot.yml
alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
alfresco-transform-misc/alfresco-transform-misc/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
alfresco-transform-tika/alfresco-transform-tika/pom.xml
alfresco-transformer-base/pom.xml
pom.xml

Replaced fabric8-maven-plugin with docker-maven-plugin and performed pom cleanup:
* moved configurations from the plugin to the execution level to avoid overlap
* removed duplicated execution of spring-boot:repackage
Ref. ATS-864

ATS-864: Switch from fabric8 to docker mvn plugin

---

alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/AIOTransformRegistry.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java
pom.xml

The t-config returned by the T-Router & T-Engines should include directAccessUrl as an optional transform option when the T-engine supports it.

ACS-2587 Include directAccessUrl in T-Config if supported

---

pom.xml

* Pick up t-model 1.4.12 which has the check for this field
[trigger release] 2.5.7-A5

ACS-2494 sourceReference may now be null with direct access urls

---

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/java/org/alfresco/transformer/AIOTransformRegistryTest.java
alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/java/org/alfresco/transformer/ImageMagickController.java
alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/java/org/alfresco/transformer/LibreOfficeController.java
alfresco-transform-misc/alfresco-transform-misc-boot/src/main/java/org/alfresco/transformer/MiscController.java
alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/java/org/alfresco/transformer/AlfrescoPdfRendererController.java
alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/TikaController.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
alfresco-transformer-base/src/main/java/org/alfresco/transformer/executors/Transformer.java

Set the size of a transform result in the Reply to the t-router.
Tidy up code: Avoid having to add the transformName to the transformOptions in the Controller class and then remove it in Transformer interface.

ACS-3118  Check the size of intermmitent results in a pipeline

---

engines/base/src/main/java/org/alfresco/transform/base/registry/TransformConfigFilesHistoric.java

It was needed for proper processing of ConfigurationProperties annotation and allowing for TRANSFORMER_ROUTES_ADDITIONAL_<engineName> for backwards compatibility. Spring mechanism takes the "transform.routes" gets the "additional" as a setting and adds to map ("ai", configFile). Without this get, the spring mechanism can't add this property due to no access to additional variable

ACS-3476: Re-adding a getAdditional method

---

engines/base/src/test/java/org/alfresco/transform/base/TransformControllerAllInOneTest.java
engines/base/src/test/java/org/alfresco/transform/base/transform/FragmentHandlerTest.java

Fixes the occasional race condition between the test looking for the custom transformer vs ATS adding the custom transformer to the registry:
https://github.com/Alfresco/alfresco-transform-core/blob/babe26b0ba29a40fa8478813a5e416ec7930352e/engines/base/src/main/java/org/alfresco/transform/base/registry/TransformRegistry.java#L154-L162
**Example of failure before the fix**: https://github.com/Alfresco/alfresco-transform-core/actions/runs/4279090922/jobs/7457207601#step:11:956
**Relevant error**: 
```
05:06:47.533 [main] DEBUG o.a.t.common.TransformerDebug - e1                  Error: No transforms for: application/pdf (5 bytes) -> image/jpeg 
05:06:47.534 [main] DEBUG o.a.t.common.TransformerDebug - e1                Finished in 0 ms
```

ACS-4739 Fix intermittent tests failures due to CustomTransformers

---

pom.xml

Apart from `snakeyaml` there were some adjustments in `jackson` dependencies needed.

ACS-4938: Bump snakeyaml

---

engines/misc/pom.xml
engines/tika/pom.xml
pom.xml

Bumping Tika, PDFBox, POI and commons-compress to the latest non-major upgrade. Bumping all of these together as some of their dependencies are intertwined and it's a faster way of verifying everything still works after the upgrade + the dependency tree looks fairly clean.
**NOTES:**
- decided to omit the `bouncycastle` dependencies override as we're now relying on the same version required by Tika instead, which is way newer than the last override we started to maintain years ago. We can re-introduce this in the future if we see Tika lags considerably behind our security necessities when it comes down to `bouncycastle`, but it's not needed in this point in time as `bouncycastle 1.76` is free from known security issues.
- removed unnecessary `poi-ooxml-lite` / `poi-ooxml-schemas` …

ACS-6653 Bump Tika, PDFBox, POI and commons-compress

---

engines/aio/Dockerfile
engines/libreoffice/Dockerfile

This change has been tested on an ARM64 environment and it worked correctly.

ACS-6450 Dynamically determine ARM64 LibreOffice download link

---

.github/workflows/ci.yml

For some reason, after [this change](https://github.com/Alfresco/alfresco-transform-core/commit/7a2a7708672a65b595cb72747504b9e7deb399f3) Veracode started picking up bouncycastle and aspectjweaver as our own code instead of 3rd party library. Temporarily removing them from the package we send for scanning until this issue is resolved.

ACS-6305 Fix Pipeline scan detecting 3rd party libraries

---

_ci/cache_artifacts.sh
deprecated/alfresco-transformer-base/pom.xml
engines/aio/Dockerfile
engines/aio/pom.xml
engines/base/pom.xml
engines/example/Dockerfile
engines/example/pom.xml
engines/imagemagick/Dockerfile
engines/imagemagick/pom.xml
engines/libreoffice/Dockerfile
engines/libreoffice/pom.xml
engines/misc/pom.xml
engines/pdfrenderer/Dockerfile
engines/pdfrenderer/pom.xml
engines/tika/Dockerfile
engines/tika/pom.xml
model/pom.xml
pom.xml

As per title. My best guess is that this is required to make the Transform Aspose Spring Boot migration happen, as the previous version of Transform Core & Service that are used there are still using the older Spring Boot version, causing library conflict issues!

ACS-8421 [release] Transform Core 5.1.4-A1 [skip tests]

---

_ci/cache_artifacts.sh
engines/aio/Dockerfile
engines/example/Dockerfile
engines/libreoffice/Dockerfile
engines/pdfrenderer/Dockerfile
engines/tika/Dockerfile

Replacing URLs that are now invalid due to deprecated APIs in Nexus 3.

Update Nexus URLs after the migration

---

.github/workflows/ci.yml

Migrate from `Node16` to `Node20`.
Bump `actions/upload-artifact` to **v4**.
Additionally: upgrading the version to the latest for other actions from the `alfresco-build-tools`.

ACS-8674 Deal with upcoming GitHub Actions deprecations

---

deprecated/alfresco-transformer-base/src/main/java/org/alfresco/transformer/messaging/MessagingInfo.java
deprecated/alfresco-transformer-base/src/main/resources/application.yaml
docs/external-engine-configuration.md
docs/t-engine-scaling.md
engines/base/src/main/java/org/alfresco/transform/base/messaging/MessagingInfo.java
engines/base/src/main/resources/application.yaml

https://hyland.atlassian.net/browse/ACS-9839
Also see https://github.com/Alfresco/alfresco-transform-service/pull/1067

[ACS-9839] Introduced ACTIVEMQ_URL_PARAMS to avoid the need to override spring.activemq.broker-url directly

---

deprecated/alfresco-transformer-base/src/main/java/org/alfresco/transformer/messaging/MessagingInfo.java
deprecated/alfresco-transformer-base/src/main/resources/application.yaml
engines/base/src/main/java/org/alfresco/transform/base/messaging/MessagingInfo.java
engines/base/src/main/resources/application.yaml

No env params:
```
2025-07-25T13:11:05.283+02:00  INFO 12220 --- [           main] o.a.t.base.messaging.MessagingInfo       : JMS client is DISABLED - ACTIVEMQ_URL is not set
2025-07-25T13:11:05.284+02:00  INFO 12220 --- [           main] o.a.t.base.messaging.MessagingInfo       : ACTIVEMQ_URL_PARAMS is not set
2025-07-25T13:11:05.284+02:00  INFO 12220 --- [           main] o.a.t.base.messaging.MessagingInfo       : spring.activemq.broker-url='nio://localhost:61616?jms.watchTopicAdvisories=false'
```
ACTIVEMQ_URL=nio://localhost:61616;ACTIVEMQ_URL_PARAMS=
```
2025-07-25T13:19:15.125+02:00  INFO 13133 --- [           main] o.a.t.base.messaging.MessagingInfo       : JMS client is ENABLED - ACTIVEMQ_URL ='nio://localhost:61616'
2025-07-25T13:19:15.125+02:00  INFO 13133 --- [           main] …
```

[ACS-9839] Additional logging
