Alfresco/alfresco-transform-core

alfresco-docker-alfresco-pdf-renderer/src/main/resources/application-default.yaml, alfresco-docker-alfresco-pdf-renderer/src/main/resources/application.properties, alfresco-docker-imagemagick/src/main/resources/application-default.yaml, alfresco-docker-imagemagick/src/main/resources/application.properties, alfresco-docker-libreoffice/src/main/resources/application-default.yaml, alfresco-docker-libreoffice/src/main/resources/application.properties, alfresco-docker-tika/src/main/resources/application-default.yaml, alfresco-docker-tika/src/main/resources/application.properties, alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java, alfresco-transformer-base/src/main/resources/application.yaml
- ignore empty fields during serialization
- changed application.properties files to application-default.yaml
=> ATS-448 : Small T-Engine configuration improvements

alfresco-docker-transform-misc/src/main/java/org/alfresco/transformer/transformers/SelectingTransformer.java, alfresco-docker-transform-misc/src/test/java/org/alfresco/transformer/MiscControllerTest.java
Transformers should not throw an exception when source and target files are empty
=> REPO-4331: Update target file size check

alfresco-docker-tika/pom.xml, alfresco-docker-tika/src/test/java/org/alfresco/transformer/TikaControllerTest.java, alfresco-docker-tika/src/test/resources/quick.txt
- upgrade tika
- upgrade poi
- fix/update test resource for PDF parsing
(multi-page PDF parsing was changed in tika-parsers 1.21)
=> ATS-480 : Update to Tika 1.21 and matching POI

alfresco-docker-alfresco-pdf-renderer/pom.xml, alfresco-docker-imagemagick/pom.xml, alfresco-docker-libreoffice/pom.xml, alfresco-docker-tika/pom.xml, alfresco-docker-transform-misc/pom.xml, alfresco-transformer-base/pom.xml, pom.xml
=> ATS-490 : ATS: T-Engines - release 2.1.0-RC1

alfresco-docker-alfresco-pdf-renderer/pom.xml, alfresco-docker-imagemagick/pom.xml, alfresco-docker-libreoffice/pom.xml, alfresco-docker-tika/pom.xml, alfresco-docker-transform-misc/pom.xml, alfresco-transformer-base/pom.xml, pom.xml
* ATS-490 : ATS: T-Engines - release 2.1.0-RC1
- releasing
=> ATS-490 : ATS: T-Engines - release 2.1.0-RC1 (#101)

.travis.yml, _ci/settings.xml
- update settings.xml with missing servers
- remove *install* phase from *company_release* jobs
- use regex for matching support branches
- update deploy tasks
=> ATS-586: Update Travis build configuration

pom.xml
=> ATS-654 : ATS-649: Release Transform Model 1.0.2.8 component library

alfresco-docker-alfresco-pdf-renderer/Dockerfile, alfresco-docker-imagemagick/Dockerfile, alfresco-docker-libreoffice/Dockerfile, alfresco-docker-tika/Dockerfile, alfresco-docker-transform-misc/Dockerfile
- 11.0.1-openjdk-centos-7-72b88c6f1f4c
=> ATS-655: Security: DEPLOY-924 - Update Dockerfiles to new Java Base Image

pom.xml
=> ATS-649 : Release T-Engines (T-Core) 2.1.1 [trigger release]

alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/java/org/alfresco/transformer/OptionsBuilder.java, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickControllerTest.java
Subject to a test related discussion with the team.
=> WIP-ATS-688: Negate OptionsBuilder's maintainAspectRatio boolean

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-imagemagick/alfresco-transform-imagemagick/src/main/java/org/alfresco/transformer/executors/ImageMagickCommandExecutor.java, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/java/org/alfresco/transformer/executors/LibreOfficeJavaExecutor.java, alfresco-transform-misc/alfresco-transform-misc-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/SelectingTransformer.java, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/src/main/java/org/alfresco/transformer/executors/PdfRendererCommandExecutor.java, alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/TikaJavaExecutor.java
=> ATS-706: Transform AIO - fix license log messages to be consistent on startup

alfresco-transform-misc/alfresco-transform-misc-boot/src/main/java/org/alfresco/transformer/Application.java, alfresco-transformer-base/src/main/java/org/alfresco/transformer/logging/StandardMessages.java
- also minor fix for Misc to be consistent with other T-Engines
- see also ATS-711
=> ATS-665: Update standard license log message on startup for all T-Engines

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
* Fix controller processTransform() method
=> ATS-711: Fix typos and resulting broken functionality

alfresco-transform-imagemagick/alfresco-transform-imagemagick/src/main/resources/imagemagick_engine_config.json, alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/resources/libreoffice_engine_config.json
* add commandOptions for backwards compatibility
* add missing html to pdf support for libreoffice
=> ATS-707: Update engine config

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerImageMagickTest.java, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerTikaTest.java, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOTikaTransformationIT.java, alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml, alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaControllerTest.java, alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaTransformationIT.java
Runs the Tika transformer tests against the new All in One transformer
=> ATS-702 Add AIO tests from Tika

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerPdfRendererTest.java, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOPdfRendererIT.java, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/test/java/org/alfresco/transformer/AlfrescoPdfRendererControllerTest.java, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/test/java/org/alfresco/transformer/AlfrescoPdfRendererTransformationIT.java, pom.xml
Runs the Pdf Renderer transformer tests against the new All in One transformer
=> ATS-702 Add AIO tests from Pdf Renderer

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/resources/application-default.yaml, pom.xml
Updated IMAGEMAGICK_VERSION reference in both Dockerfiles
=> ATS-735: Update to ImageMagick 7.0.10-11 distro bins

_ci/static_analysis.sh
- only run for Core AIO (which combines the other x5)
- TODO see if we can tweak further and not upload -tests.jar
- see also ATS-468, ATS-718
=> ATS-764: Tweak Veracode SAST to see if we can get it to succeed

alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickTransformationIT.java
- add unit test for image/tiff -> image/*
- note: some require request to contain transform options (startPage) for single page output
=> ATS-770: Tech Debt: Transforms - Tiff (via ImageMagick) - add unit tests for supported transforms

alfresco-transform-misc/alfresco-transform-misc/pom.xml, alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml, alfresco-transform-tika/alfresco-transform-tika/pom.xml, pom.xml
- Replace `poi-ooxml-schemas` with `ooxml-schemas`
=> MNT-21487: Switch from smaller schemas jar (poi-ooxml-schemas) to the full jar (ooxml-schemas)

alfresco-transformer-base/README.md
See changes, but simpler to read: https://github.com/Alfresco/alfresco-transform-core/blob/feature/repo-5201_how_to_create_a_t_engine/alfresco-transformer-base/README.md
=> REPO-5201 Update README on how to create a T-Engine

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOCustomConfig.java, alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/java/org/alfresco/transformer/LibreOfficeController.java, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/resources/application-default.yaml, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/java/org/alfresco/transformer/LibreOfficeControllerTest.java, alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/java/org/alfresco/transformer/executors/LibreOfficeJavaExecutor.java, alfresco-transformer-base/src/main/resources/application.yaml, docs/external-engine-configuration.md, pom.xml
Reduce default value of timeout for libreoffice from 2000min to 20min
Add option to configure libreoffice timeout externally.
=> MNT-21869 libreoffice timeout set too high

pom.xml
Reverts Alfresco/alfresco-transform-core#198
=> Revert "Bump fabric8-maven-plugin from 4.4.0 to 4.4.1"

.travis.yml, _ci/build.sh, _ci/release.sh, _ci/settings.xml, _ci/test.sh
- Add Maven Central to top of repo search list
- Disable Maven connection pool
=> ATS-851: Improve build reliability

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml, alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml, alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
See [ACS-1185](https://alfresco.atlassian.net/browse/ACS-1185)
=> ACS-1185 Update activemq image to 5.16.1

.travis.yml, pom.xml
* Include alfresco-jodconverter-core.version:3.0.1.12
=> ACS-813 "UpdateDocMode", UpdateDocMode.NO_UPDATE

models/README.md
- tweak text to be consistent with T-Service
- note: for now a copy of files (sourced from Repo)
- we can look to remove &/or rationalise in the future (depending on how quickly ACS service packs are released etc)
=> ATS-892 / ATS-909: Add IPTC model to ATS zip

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile, alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile, alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
=> ATS-912 [trigger release] 2.4.0

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml, alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml, alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml, alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml, alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml, alfresco-transform-misc/alfresco-transform-misc/pom.xml, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml, alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml, alfresco-transform-tika/alfresco-transform-tika/pom.xml, alfresco-transformer-base/pom.xml, pom.xml
=> ATS-935 / ATS-936: Prep for T-Core 2.5.0 release

README.md
- list of T-Engines
- links to ACS Deployment
=> ATS: tweak top-level T-Core README

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile, alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile, alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
Bump alfresco-java-base image version
=> ATS-952: Bump alfresco-java-base image version

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOCustomConfig.java, alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/AIOTransformRegistry.java, alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/java/org/alfresco/transformer/AIOTransformRegistryTest.java, alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java, alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java, pom.xml
* Use CombinedTransformConfig from the transform-model rather than trying to combine TransformConfig in this project
=> ACS-1998 Enhance the transform config

_ci/cache_artifacts.sh
- in three places (it looks like 3rd place was missed as part of ATS-935)
=> ATS-935: Fix LibreOffice version in CI script

alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java, alfresco-transformer-base/src/main/java/org/alfresco/transformer/config/WebApplicationConfig.java, pom.xml
=> ACS-2479 AI Transformers do not start if built using ATS 1.5.0 components

alfresco-transform-misc/alfresco-transform-misc/pom.xml, alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/executors/TikaOfficeDetectParser.java, pom.xml
Linked issue - https://alfresco.atlassian.net/browse/ACS-2556
Changes already done for the ticket in community repo - https://github.com/Alfresco/alfresco-community-repo/pull/1155
Makes these redundant:
https://github.com/Alfresco/alfresco-transform-core/pull/637
https://github.com/Alfresco/alfresco-transform-core/pull/601
https://github.com/Alfresco/alfresco-transform-core/pull/573
=> ACS-2556 Bump Apache POI, Apache Tika, and PDFBox

alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml, alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml, alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml, alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml, alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml, alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml, pom.xml
See [ACS-3307](https://alfresco.atlassian.net/browse/ACS-3307)
=> ACS-3307 Upgrade ActiveMQ to 5.17.1

engines/aio/src/test/java/org/alfresco/transform/aio/AIOTikaTest.java, engines/misc/src/main/java/org/alfresco/transform/misc/transformers/ImageToPdfTransformer.java, engines/misc/src/main/resources/misc_engine_config.json, engines/misc/src/test/java/org/alfresco/transform/misc/transformers/ImageToPdfTransformerTest.java, engines/misc/src/test/java/org/alfresco/transform/misc/util/ArgumentsCartesianProduct.java, model/src/main/java/org/alfresco/transform/common/RequestParamMap.java
https://alfresco.atlassian.net/browse/ATS-996
=> ATS-996: TIFF to PDF - invalid output format

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
Release contains upgrade to Java 17
=> [release] ACS-5198: Release T-Core (T-Engines) 3.2.0-A1

engines/imagemagick/src/main/java/org/alfresco/transform/imagemagick/transformers/ImageMagickTransformer.java, engines/imagemagick/src/test/java/org/alfresco/transform/imagemagick/ImageMagickTransformationIT.java
- set startPage and endPage to 0 as default for NON multi-page image targets
=> MNT-23660: TIFF files fail to transform into PNG & JPG

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
https://alfresco.atlassian.net/browse/ACS-5409
=> ACS-5409: Release T-Core (T-Engines) 4.0.0-A1 [release]

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
=> ACS-5943 [release] Transform Core 4.1.0-A1

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
=> ACS-5944 [release] Transform Core 4.1.0-M1

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
=> ACS-5944 Set next development version

engines/aio/Dockerfile, engines/libreoffice/Dockerfile
[ACS-6450](https://alfresco.atlassian.net/browse/ACS-6450)
[ACS-6450]: https://alfresco.atlassian.net/browse/ACS-6450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACS-6450 - Bumped LibreOffice package version

engines/base/src/main/java/org/alfresco/transform/base/config/MTLSConfig.java, pom.xml
=> Upgrade spring boot to 3.2.2

_ci/cache_artifacts.sh, engines/aio/Dockerfile, engines/example/Dockerfile, engines/libreoffice/Dockerfile, engines/pdfrenderer/Dockerfile, engines/tika/Dockerfile
Same as https://github.com/Alfresco/alfresco-transform-core/pull/983.
=> Update Nexus URLs after the migration

.github/workflows/ci.yml, engines/pdfrenderer/src/main/java/org/alfresco/transform/pdfrenderer/PdfRendererOptionsBuilder.java, scripts/check-format-and-headers.sh
Expected pre-commit failure: https://github.com/Alfresco/alfresco-transform-core/actions/runs/11555591812/job/32161367965 ❌ 
Pre-commit passed for an empty commit: https://github.com/Alfresco/alfresco-transform-core/actions/runs/11555806366/job/32162061452 ✅
=> ACS-8920 Fix pre-commit for empty commits

pom.xml
Reverts Alfresco/alfresco-transform-core#1006
=> Revert "Bump org.apache.commons:commons-compress from 1.26.2 to 1.27.1"

docs/t-engine-scaling.md
https://hyland.atlassian.net/browse/ACS-9699
=> ACS-9699 Document horizontal and vertical scaling of T-Engines

deprecated/alfresco-transformer-base/pom.xml, engines/aio/pom.xml, engines/base/pom.xml, engines/example/pom.xml, engines/imagemagick/pom.xml, engines/libreoffice/pom.xml, engines/misc/pom.xml, engines/pdfrenderer/pom.xml, engines/tika/pom.xml, model/pom.xml, pom.xml
[ACS-9819](https://hyland.atlassian.net/browse/ACS-9819)
[ACS-9819]: https://hyland.atlassian.net/browse/ACS-9819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Please [release] 5.2.0-A.1 [skip tests]

engines/misc/src/main/java/org/alfresco/transform/misc/transformers/TextToPdfContentTransformer.java, engines/misc/src/test/java/org/alfresco/transform/misc/MiscTest.java, engines/misc/src/test/java/org/alfresco/transform/misc/MiscTransformsIT.java, engines/misc/src/test/java/org/alfresco/transform/misc/transformers/ImageToPdfTransformerTest.java, engines/misc/src/test/java/org/alfresco/transform/misc/transformers/TextToPdfContentTransformerTest.java, engines/tika/src/main/java/org/alfresco/transform/tika/metadata/extractors/MailMetadataExtractor.java, engines/tika/src/main/java/org/alfresco/transform/tika/parsers/ExifToolParser.java, pom.xml
more information about changes: https://hyland.atlassian.net/browse/ACS-10169?focusedCommentId=2546799
=> ACS-10169 Bump tika to 3.x
